spring:
  application:
    name: RabbitMQ Producer Application
  datasource:
    url: jdbc:postgresql://localhost:5432/rabbitmq_springboot
    username: postgres
    password: postgres
  data:
    jdbc:
      repositories:
        enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_updates: true
        generate_statistics: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# configuring the application server
server:
  port: 9090
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path: /rabbitmq-producer
